// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hello2': string;
  'hello2-text': string;
  'hello_class': string;
}
export const cssExports: CssExports;
export default cssExports;
